"""Generate the MCP environment reference from the runtime settings schema."""

from __future__ import annotations

from pathlib import Path

from recall_mcp.settings import render_env_example


ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "docs" / "ENVIRONMENT_GENERATED.md"


def main() -> None:
    TARGET.write_text(
        "# Runtime environment reference\n\n"
        "This file is generated by `python scripts/generate_env_docs.py`.\n\n"
        + render_env_example()
        + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
