"""Generate the MCP environment reference from the runtime settings schema."""

from __future__ import annotations

from pathlib import Path

from recall_mcp.settings import render_env_example


ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "docs" / "ENVIRONMENT_GENERATED.md"


def main() -> None:
    content = (
        "# Runtime environment reference\n\n"
        "This file is generated by `python scripts/generate_env_docs.py`.\n\n"
        + render_env_example()
        + "\n"
    )
    with TARGET.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)


if __name__ == "__main__":
    main()
