"""Bump the version everywhere it is written, and stop before anything irreversible.

**What this exists to fix.** The version is hand-maintained in seven places. Post-tag automation is
already good: `release.yml` builds, smoke-tests, publishes to PyPI behind a reviewer and creates the
GitHub Release from the CHANGELOG. Everything BEFORE the tag was a person editing seven files from
memory, and the record shows what that costs. Releasing 0.9.7 bumped `pyproject.toml` and left
`recall/__init__.py` at 0.9.6, which is not a cosmetic mismatch: the wizard pins
`recall.__version__` into the Dockerfile it generates, so the installer provisions a container
pinned to a version that either does not exist on PyPI or is a different recall than the one
building the generations.

**What it deliberately does NOT do.** It never commits, never tags, never pushes and never
publishes. It edits tracked files and prints the remaining commands.

Three reasons, and the first is the one that matters:

1. **A version on PyPI is permanent.** A tag push starts a publish that a yank cannot undo, so the
   irreversible step stays a thing a person types deliberately.
2. **`git_clone_race_guard.py` refuses a tag and a push in one command**, because at the moment the
   guard runs the tag does not exist and cannot be told from a branch. So the tail of a release is
   two commands by construction, and a script that tried to do it in one would be fighting a guard
   that is right.
3. Everything this script does IS reversible, with `git checkout -- .`, precisely because it stops
   where it does.

**The version sites are defined here and imported by the test that guards them**
(`tests/test_version_is_single_sourced.py`). One definition, because two lists of the same seven
files is the failure this repository keeps paying for: the checker and the bumper would drift, and
the drift would surface as a release that bumped six of seven.

Usage:

    python scripts/release.py 0.9.9              # show the plan, change nothing
    python scripts/release.py 0.9.9 --apply      # write the files, then stop
"""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys
import tomllib
from dataclasses import dataclass

REPO = pathlib.Path(__file__).resolve().parent.parent

#: Files that are NOT bumped even though they carry the version string.
#:
#: ⛔ `scripts/agent_ab_build_workspaces.py` generates a benchmark fixture whose task is literally
#: "bump recall/version.py from 0.9.7 to 0.9.8". Its literals are fixture DATA. Bumping them would
#: ask an agent to bump a file that already holds the target value, and every session would pass
#: for the wrong reason. `test_version_is_single_sourced` skips it for the same reason and says so.
EXCLUDED = frozenset({"scripts/agent_ab_build_workspaces.py"})


@dataclass(frozen=True)
class Site:
    """One place the version is written, and how to recognise it there.

    `pattern` is anchored on the surrounding syntax rather than on the bare number. A bare version
    appears in prose all over this repository as a historical measurement, and rewriting those
    would falsify a record of what was measured rather than update a declaration.
    """

    path: str
    #: A regex with exactly one group: the version. Applied with `re.MULTILINE`.
    pattern: str
    #: How many times it must match. A count that changes is a file whose shape changed, and
    #: silently bumping fewer sites than expected is the whole failure mode here.
    occurrences: int


#: Every hand-maintained copy. Keep in step with `known` in `tests/test_version_is_single_sourced.py`,
#: which imports this tuple rather than restating it.
#:
#: ⚠️ `uv.lock` carries the version because the project is its own dependency. It is regenerated by
#: `uv lock`, NOT edited here: a hand-edited lockfile disagrees with its own hashes, and CI runs
#: `uv lock --check` as a hard gate. It is listed so the count is honest and so `--apply` can tell
#: you to run the command.
SITES: tuple[Site, ...] = (
    Site("pyproject.toml", r'^version = "([0-9][^"]*)"', 1),
    Site("recall/__init__.py", r'^__version__ = "([0-9][^"]*)"', 1),
    Site("server.json", r'"version": "([0-9][^"]*)"', 2),
    # ⛔ The THIRD copy in `server.json`, and it is not a `"version":` key. It is the pin inside
    # `runtimeArguments`, of the form `recall-rag[mcp,fastembed]==X.Y.Z`, which is the exact string
    # `uvx` installs. Written with a placeholder rather than the live number on purpose: a literal
    # would be a seventh copy of the version, and `test_every_hand_maintained_copy_of_the_version_
    # is_accounted_for` correctly flagged this file when the first draft spelled it out.
    #
    # Caught by `test_the_bumper_recognises_the_version_actually_in_each_file`, which failed on the
    # occurrence count while this script still claimed three matches for the key pattern. Without
    # this entry a release would publish a registry entry ADVERTISING the new version while telling
    # every client to install the previous one, which is the silent version skew
    # `recall/wizard/stack.py` already carries a docstring about.
    Site("server.json", r'recall-rag\[[^\]]*\]==([0-9][^"\s]*)', 1),
    Site("CITATION.cff", r"^version: ([0-9][^\s]*)", 1),
    Site("plugin/.claude-plugin/plugin.json", r'"version": "([0-9][^"]*)"', 1),
    Site(".claude-plugin/marketplace.json", r'"version": "([0-9][^"]*)"', 1),
)

#: Regenerated rather than edited. See the note on `SITES`.
REGENERATED = ("uv.lock",)

VERSION_RE = re.compile(r"^\d+\.\d+\.\d+$")


class Refusal(RuntimeError):
    """A precondition the release does not meet, phrased so the reader can act on it."""


def current_version() -> str:
    document = tomllib.loads((REPO / "pyproject.toml").read_text(encoding="utf-8"))
    return str(document["project"]["version"])


def _git(*args: str) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=REPO,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=True,
    )
    return result.stdout.strip()


def check_preconditions(version: str, *, allow_dirty: bool) -> list[str]:
    """Everything that makes a release wrong, checked before a byte is written.

    Returns advisory notes. Anything that must stop the release raises `Refusal` instead, because
    a warning printed above a wall of output is a warning nobody reads.
    """
    notes: list[str] = []

    if not VERSION_RE.match(version):
        raise Refusal(f"{version!r} is not X.Y.Z. The tag and the PyPI release are built from it.")

    current = current_version()
    if version == current:
        raise Refusal(f"pyproject.toml already says {version}. Nothing to bump.")
    if _compare(version, current) <= 0:
        raise Refusal(
            f"{version} is not greater than the current {current}. PyPI refuses a version it has "
            "already seen, and it refuses it AFTER the tag exists."
        )

    # A tag that already exists means this version was, or nearly was, released. Creating it again
    # is how a published version gets quietly re-pointed at different code.
    if f"v{version}" in _git("tag", "--list", f"v{version}").split():
        raise Refusal(f"tag v{version} already exists locally. This version has been cut before.")

    if not allow_dirty and _git("status", "--porcelain"):
        raise Refusal(
            "the working tree is dirty. A release commit should contain the bump and nothing "
            "else, so commit or stash first, or pass --allow-dirty if you know why."
        )

    if not _changelog_section(version):
        raise Refusal(
            f"CHANGELOG.md has no `## [{version}]` section. `release.yml` builds the GitHub "
            "Release body from it, and without one the release ships auto-generated notes."
        )

    # A BREAKING change may not ship as a patch bump. Pre-1.0 SemVer puts breaks in the MINOR,
    # so if the notes staged under `## [Unreleased]` say BREAKING and this bump moves only the
    # patch component, refuse: an operator upgrading `0.9.8 -> 0.9.9` reads that as safe, and
    # the MCP registry pins the exact version, so the break arrives disguised as a patch.
    if _unreleased_has_breaking() and _is_patch_bump(current, version):
        raise Refusal(
            f"CHANGELOG's [Unreleased] section is marked BREAKING, but {current} -> {version} is a "
            "patch bump. Pre-1.0, a break goes in the MINOR (e.g. 0.10.0), or the registry pin "
            "ships it to clients as a patch. Bump the minor, or move the BREAKING note if it is "
            "not actually breaking."
        )

    branch = _git("rev-parse", "--abbrev-ref", "HEAD")
    if branch != "master":
        notes.append(f"on branch {branch!r}, not master. Releases are cut from master.")

    return notes


def _compare(left: str, right: str) -> int:
    a, b = tuple(int(p) for p in left.split(".")), tuple(int(p) for p in right.split("."))
    return (a > b) - (a < b)


def _changelog_section(version: str) -> bool:
    text = (REPO / "CHANGELOG.md").read_text(encoding="utf-8")
    return f"## [{version}]" in text


def _unreleased_has_breaking() -> bool:
    """True when the CHANGELOG's `## [Unreleased]` section contains a BREAKING marker."""
    text = (REPO / "CHANGELOG.md").read_text(encoding="utf-8")
    start = text.find("## [Unreleased]")
    if start == -1:
        return False
    nxt = text.find("\n## [", start + 1)
    section = text[start : nxt if nxt != -1 else len(text)]
    return "BREAKING" in section


def _is_patch_bump(current: str, version: str) -> bool:
    """True when only the patch component changes (same major and minor)."""
    cur = tuple(int(p) for p in current.split("."))
    new = tuple(int(p) for p in version.split("."))
    return cur[:2] == new[:2] and new[2] != cur[2]


def plan(version: str) -> list[tuple[Site, str, int]]:
    """What would change: one row per site, with the version found and the match count.

    Raises rather than skipping when a site's count is wrong. A file whose shape changed is one
    where a silent partial bump is the likely outcome, and a partial bump is this script's entire
    reason to exist.
    """
    rows: list[tuple[Site, str, int]] = []
    for site in SITES:
        path = REPO / site.path
        if not path.is_file():
            raise Refusal(f"{site.path} is missing. It is one of the places the version lives.")
        found = re.findall(site.pattern, path.read_text(encoding="utf-8"), re.MULTILINE)
        if len(found) != site.occurrences:
            raise Refusal(
                f"{site.path} matched {len(found)} times, expected {site.occurrences}. Its shape "
                "changed, so this script can no longer tell which occurrences are declarations."
            )
        distinct = set(found)
        if len(distinct) != 1:
            raise Refusal(f"{site.path} carries several versions {sorted(distinct)}; fix it first.")
        rows.append((site, found[0], len(found)))
    return rows


def apply(version: str) -> list[str]:
    """Rewrite every site. Returns the paths changed."""
    changed: list[str] = []
    for site, _found, _count in plan(version):
        path = REPO / site.path
        text = path.read_text(encoding="utf-8")
        updated = re.sub(
            site.pattern,
            lambda match: match.group(0).replace(match.group(1), version),
            text,
            flags=re.MULTILINE,
        )
        if updated != text:
            # LF and no trailing-newline surprises: several of these files are JSON this repository
            # writes with LF everywhere, and a platform newline here rewrites every line.
            path.write_text(updated, encoding="utf-8", newline="\n")
            changed.append(site.path)
    return changed


def main(argv: list[str] | None = None) -> int:
    # ⛔ **This crashed a real run, AFTER the files were written.** The closing advice carries a
    # `⚠️`, and a Windows console is cp1252, so `print` raised `UnicodeEncodeError` at the moment
    # the operator most needed to read what to do next: seven files already bumped, the tag advice
    # never printed, and a traceback that looks like the bump itself failed.
    #
    # Same fix and same reason as `recall/cli.py`, including `errors=`: reconfiguring the encoding
    # RESETS errors to strict, so setting only `encoding` would trade this crash for the next one.
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8", errors="backslashreplace")

    parser = argparse.ArgumentParser(
        prog="release.py",
        description="Bump the version in every file that carries it, then stop.",
    )
    parser.add_argument("version", help="the new version, X.Y.Z")
    parser.add_argument(
        "--apply",
        action="store_true",
        help="write the files. Without this, the plan is printed and nothing changes.",
    )
    parser.add_argument(
        "--allow-dirty",
        action="store_true",
        help="proceed with an unclean working tree",
    )
    args = parser.parse_args(argv)

    try:
        notes = check_preconditions(args.version, allow_dirty=args.allow_dirty)
        rows = plan(args.version)
    except Refusal as refusal:
        print(f"refused: {refusal}", file=sys.stderr)
        return 1
    except subprocess.CalledProcessError as exc:
        print(f"refused: git failed: {exc.stderr or exc}".strip(), file=sys.stderr)
        return 1

    for note in notes:
        print(f"note: {note}")

    print(f"\n{current_version()} -> {args.version}\n")
    for site, found, count in rows:
        times = "" if count == 1 else f"  ({count} occurrences)"
        print(f"  {site.path:42} {found}{times}")
    for path in REGENERATED:
        print(f"  {path:42} regenerated by `uv lock`")

    if not args.apply:
        print("\nNothing written. Re-run with --apply to make these changes.")
        return 0

    changed = apply(args.version)
    print(f"\nwrote {len(changed)} files.\n")
    print("Next, in this order. None of it has happened yet:\n")
    print("  uv lock                                   # the lockfile carries the version too")
    print("  python -m pytest tests/ -q                # the version guards are in here")
    print(f"  git add -u && git commit -m 'Release {args.version}'")
    print(f"  git tag -s v{args.version} -m '<what this release is for>'")
    print(f"  git push origin v{args.version}           # SEPARATE command: see the module docstring")
    print("\n⚠️  The tag push publishes to PyPI, behind a reviewer, and a version there is")
    print("    permanent. Nothing before that point is irreversible; `git checkout -- .` undoes")
    print("    everything this script just wrote.")
    print("\n    After the release lands, publish the MCP registry entry by hand: the")
    print("    `Publish MCP Registry` workflow is workflow_dispatch only, which is why the")
    print("    registry sat at 0.9.5 while 0.9.8 shipped.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
