"""Generate a repeatable import map for the maintained RE-call packages."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT_PACKAGES = (
    "recall",
    "recall_mcp",
    "recall_agent",
    "recall_hooks",
    "recall_interop",
    "recall_consistency",
)


def package_root(module: str) -> str:
    return module.split(".", 1)[0]


def build_map() -> str:
    import grimp

    graph = grimp.build_graph(*ROOT_PACKAGES)
    modules = sorted(graph.modules)

    fan_in = sorted(
        (
            (len(graph.find_upstream_modules(module)), module)
            for module in modules
        ),
        key=lambda item: (-item[0], item[1]),
    )
    direct_importers = sorted(
        (
            (len(graph.find_modules_directly_imported_by(module)), module)
            for module in modules
        ),
        key=lambda item: (-item[0], item[1]),
    )
    cross_edges = sorted(
        (
            module,
            imported,
        )
        for module in modules
        for imported in graph.find_modules_directly_imported_by(module)
        if package_root(module) != package_root(imported)
    )

    lines = [
        "# Generated Architecture Map",
        "",
        "This file is generated by `python tools/architecture_map.py`.",
        "It records static import evidence. Runtime plugin loading, reflection, and configuration",
        "driven edges may not appear here. Review the source and tests before treating an edge as a",
        "design violation.",
        "",
        "## Scope",
        "",
        f"Packages: {', '.join(f'`{name}`' for name in ROOT_PACKAGES)}",
        f"Modules: {len(modules)}",
        f"Cross package edges: {len(cross_edges)}",
        "",
        "## Highest fan in modules",
        "",
        "| Upstream modules | Module |",
        "|---:|---|",
    ]
    lines.extend(
        f"| {count} | `{module}` |"
        for count, module in fan_in[:40]
    )

    lines.extend(
        [
            "",
            "## Modules with the most direct imports",
            "",
            "| Direct imports | Module |",
            "|---:|---|",
        ]
    )
    lines.extend(
        f"| {count} | `{module}` |"
        for count, module in direct_importers[:40]
    )

    lines.extend(
        [
            "",
            "## Cross package edges",
            "",
            "These edges are the first review queue for ownership and dependency direction.",
            "They are observations, not automatic failures.",
            "",
            "| Importer | Imported module |",
            "|---|---|",
        ]
    )
    lines.extend(f"| `{source}` | `{target}` |" for source, target in cross_edges)

    lines.extend(
        [
            "",
            "## Module inventory",
            "",
            "| Module | Direct imports | Upstream modules |",
            "|---|---:|---:|",
        ]
    )
    lines.extend(
        "| `{module}` | {direct} | {upstream} |".format(
            module=module,
            direct=len(graph.find_modules_directly_imported_by(module)),
            upstream=len(graph.find_upstream_modules(module)),
        )
        for module in modules
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the committed map is current without modifying it.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("docs/ARCHITECTURE_MAP_GENERATED.md"),
        help="Output Markdown path.",
    )
    args = parser.parse_args()
    rendered = build_map()
    if args.check:
        try:
            with args.output.open("r", encoding="utf-8", newline="") as handle:
                committed = handle.read()
        except FileNotFoundError:
            parser.error(f"architecture map does not exist: {args.output}")
        if committed != rendered:
            print(
                f"Architecture map is stale: regenerate with `python {Path(__file__).as_posix()}`",
            )
            raise SystemExit(1)
        print(f"Architecture map is current: {args.output}")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(rendered)
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
