"""Build the RE-call social preview while retaining the figure guard contract.

The committed PNG is generated by ``make_brand_assets.py``. The small SVG
compatibility surface below remains because the repository tests use it to verify
that benchmark labels stay escaped and data-bound.
"""

from __future__ import annotations

import html
import pathlib
import sys

HERE = pathlib.Path(__file__).parent
sys.path.insert(0, str(HERE))

from make_mtrag_abstention import INK, INK_MUTED, INK_SOFT, label_for  # noqa: E402

W, H = 1280, 640
BARS = (
    ("llama-3.1-8b", "field", ""),
    ("RE-call", "hero", ""),
    ("gpt-4o", "field", ""),
    ("llama-3.1-405b", "warn", "tops the table on answer quality"),
)
BAR_X = 690
BAR_MAX_W = 400
VALUE_RIGHT = 1220
ROW_TOP = 246
ROW_STEP = 82
BAR_H = 26
NOTE_DX = 158
FOOTER_TOP = 560
LABEL_PX_PER_CHAR = 9.8
COLOR = {"hero": "#D7A52A", "warn": "#D7A52A", "field": INK_MUTED}


def percent(name: str) -> float:
    return float(label_for(name).rstrip("%"))


def _check_layout() -> float:
    if not BARS:
        raise SystemExit("BARS is empty; the card needs at least one system")
    last_bottom = ROW_TOP + (len(BARS) - 1) * ROW_STEP + 12 + BAR_H
    if last_bottom > FOOTER_TOP:
        raise SystemExit(
            f"{len(BARS)} bars need {last_bottom}px but the footer starts at {FOOTER_TOP}px; "
            "drop a row or reduce ROW_STEP"
        )
    for name, _kind, note in BARS:
        if note and len(name) * LABEL_PX_PER_CHAR + 12 > NOTE_DX:
            raise SystemExit(
                f"the note on {name!r} would collide with its label; "
                f"raise NOTE_DX above {NOTE_DX} or shorten the name"
            )
    top = max(percent(name) for name, _, _ in BARS)
    if top <= 0:
        raise SystemExit("every system in BARS refuses 0 of 55; there is nothing to scale against")
    return BAR_MAX_W / top


def bars() -> str:
    parts: list[str] = []
    scale = _check_layout()
    for i, (name, kind, note) in enumerate(BARS):
        value = percent(name)
        width = value * scale
        label_y = ROW_TOP + i * ROW_STEP
        bar_y = label_y + 12
        colour = COLOR[kind]
        hero = kind == "hero"
        parts.append(
            f'<text x="{BAR_X}" y="{label_y}" font-size="19" '
            f'font-weight="{700 if hero else 500}" fill="{INK if hero else INK_SOFT}">'
            f'{html.escape(name, quote=False)}</text>'
        )
        if note:
            parts.append(
                f'<text x="{BAR_X + NOTE_DX}" y="{label_y}" font-size="16" font-weight="500" '
                f'fill="{colour}" opacity="0.85">· {html.escape(note, quote=False)}</text>'
            )
        parts.append(
            f'<rect x="{BAR_X}" y="{bar_y}" width="{BAR_MAX_W}" height="{BAR_H}" rx="6" '
            'fill="rgba(70,80,71,0.18)"/>'
        )
        parts.append(
            f'<rect x="{BAR_X}" y="{bar_y}" width="{width:.1f}" height="{BAR_H}" rx="6" '
            f'fill="{colour}" opacity="{1 if hero else 0.72}"/>'
        )
        parts.append(
            f'<text x="{VALUE_RIGHT}" y="{bar_y + 20}" text-anchor="end" font-size="26" '
            f'font-weight="700" fill="{colour if kind != "field" else INK_SOFT}">'
            f'{value:.1f}%</text>'
        )
    return "\n    ".join(parts)


_HTML = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>RE-call social preview</title>
  <style>
    html, body { margin: 0; background: #0e100f; }
    img { display: block; width: 1280px; height: 640px; }
  </style>
</head>
<body>
  <!-- The committed PNG is generated by docs/make_brand_assets.py. -->
  <img src="social_card.png" alt="RE-call social preview">
</body>
</html>
"""


def build() -> str:
    return _HTML


def main() -> None:
    from make_brand_assets import ROOT, save, social_card

    save(social_card(), ROOT / "social_card.png")
    print("wrote docs/social_card.png")


if __name__ == "__main__":
    main()
